### ISSUE TITLE
Alerts not showing in web console

### ISSUE THREAD

**Issue by unaisarakkal** [guardian/alerta#119]
I have installed alerta and web console and able to send alerts to it. Also able to list the alerts from CLI using 'alerta query'. Anyhow I am unable to see these alerts from the web console

So I created a conf file with the following content - 

[DEFAULT]
timezone = Australia/Sydney
output = json

[profile production]
endpoint = https://api.alerta.io
key = demo-key

[profile development]
endpoint = http://localhost:8080
debug = yes

And when starting the daemon alertad with the above conf, I am getting the following error -

Traceback (most recent call last):
  File "/usr/local/bin/alertad", line 9, in <module>
    load_entry_point('alerta-server==4.5.1', 'console_scripts', 'alertad')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 356, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2476, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2190, in load
    ['__name__'])
  File "/usr/local/lib/python2.7/dist-packages/alerta/app/__init__.py", line 15, in <module>
    app.config.from_pyfile('/etc/alertad.conf', silent=True)
  File "/usr/local/lib/python2.7/dist-packages/flask/config.py", line 129, in from_pyfile
    exec(compile(config_file.read(), filename, 'exec'), d.__dict__)
  File "/etc/alertad.conf", line 5
    [ profile Production ]
                       ^

**Comment by satterly** [comment]
Rename `alertad.conf` to `alerta.conf` and restart the server. In your browser check for CORS errors in the Developers JavaScript console.

**Comment by unaisarakkal** [comment]
Thank you!! daemon started. Anyhow yet to see alerts on web console

**Comment by satterly** [comment]
Please see #97, #101 and [this](http://docs.alerta.io/en/latest/authentication.html#cross-origin) if you are still having problems.
