### ISSUE TITLE
Port 8080 is hardwired

### ISSUE THREAD

**Issue by deeplook** [guardian/alerta#178]
I've installed alerta with `pip install alerta-server` on Mac OS X. Now I'm trying to run an alerta server on a port different from the default 8080, but no luck. After browsing the code I see port 8080 hardwired in this line: https://github.com/guardian/alerta/blob/ced4b0d/alerta/app/__init__.py#L97. Changing this value has the desired effect, but is still hard-wired.

Before I tried setting `ALERTA_SVR_CONF_FILE=~/.alertad.conf` with the following minimal file content:

```
[DEFAULT]
timezone = Europe/Berlin
profile = production

[profile production]
endpoint = http://localhost:8090
key = demo-key
```

But I was getting this traceback:

```
Flatbook:alerta_test_directory dinu$ ./miniconda2/bin/alertad
Traceback (most recent call last):
  File "./miniconda2/bin/alertad", line 9, in <module>
    load_entry_point('alerta-server==4.7.9', 'console_scripts', 'alertad')()
  File "/Users/dinu/alerta_test_directory/miniconda2/lib/python2.7/site-packages/setuptools-18.8.1-py2.7.egg/pkg_resources/__init__.py", line 568, in load_entry_point
  File "/Users/dinu/alerta_test_directory/miniconda2/lib/python2.7/site-packages/setuptools-18.8.1-py2.7.egg/pkg_resources/__init__.py", line 2720, in load_entry_point
  File "/Users/dinu/alerta_test_directory/miniconda2/lib/python2.7/site-packages/setuptools-18.8.1-py2.7.egg/pkg_resources/__init__.py", line 2380, in load
  File "/Users/dinu/alerta_test_directory/miniconda2/lib/python2.7/site-packages/setuptools-18.8.1-py2.7.egg/pkg_resources/__init__.py", line 2386, in resolve
  File "/Users/dinu/alerta_test_directory/miniconda2/lib/python2.7/site-packages/alerta/app/__init__.py", line 17, in <module>
    app.config.from_envvar('ALERTA_SVR_CONF_FILE', silent=True)
  File "/Users/dinu/alerta_test_directory/miniconda2/lib/python2.7/site-packages/flask/config.py", line 108, in from_envvar
    return self.from_pyfile(rv, silent=silent)
  File "/Users/dinu/alerta_test_directory/miniconda2/lib/python2.7/site-packages/flask/config.py", line 129, in from_pyfile
    exec(compile(config_file.read(), filename, 'exec'), d.__dict__)
  File "/Users/dinu/.alertad.conf", line 5
    [profile production]
                      ^
SyntaxError: invalid syntax
```

Looking into `/Users/dinu/alerta_test_directory/miniconda2/lib/python2.7/site-packages/flask/config.py:129` makes me suspect that alerta expects a Python file.

Is there any released version that works better?

**Comment by satterly** [comment]
Yes, the port is hardcoded to 8080 but the alerta server is only meant to be run on the command line during development / testing.

The alerta server requires a python file for its [configuration](http://docs.alerta.io/en/latest/configuration.html) The alerta command-line tool requires an ["ini"](http://docs.alerta.io/en/latest/cli.html) file.

**Comment by deeplook** [comment]
Ok, maybe I should read more of the docs. In any case I think that 8080 is a _very_ popular port and chances are high something is already running on it, like it was the case for me. So I would argue to add it as a command-line option to `alertad` at least.
