### ISSUE TITLE
error in management/status page

### ISSUE THREAD

**Issue by msupino** [guardian/alerta#297]
[2016-12-01 17:16:32,827] ERROR in app: Exception on /management/status [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/usr/local/lib/python2.7/dist-packages/alerta/app/auth.py", line 125, in decorated
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/alerta/app/management/views.py", line 128, in status
    metrics.extend(Counter.get_counters(format='json'))
AttributeError: 'Cursor' object has no attribute 'extend'
Exception on /management/status [GET]

started in 4.8.13

**Comment by satterly** [comment]
Fixed in Alerta server version 4.8.14 available for download now.
