### ISSUE TITLE
Rejecting allowed environments is case-sensitive.

### ISSUE THREAD

**Issue by jamtur01** [guardian/alerta#317]
If I have:

```
ALLOWED_ENVIRONMENTS = ['production', 'development', 'core']
```

And have an alert enter with:

```
:environment => 'Core'
```

It'll be rejected. I have mixed feels about whether it should or not but think enforcing case here is slightly odd?

**Comment by satterly** [comment]
That surprises me slightly. The code for the reject plugin seems to suggest otherwise ...

```
if alert.environment not in ALLOWED_ENVIRONMENTS:
    LOG.warning("[POLICY] Alert environment must be one of %s" % ', '.join(ALLOWED_ENVIRONMENTS))
    raise RejectException("[POLICY] Alert environment must be one of %s" % ', '.join(ALLOWED_ENVIRONMENTS))
```
https://github.com/guardian/alerta/blob/master/alerta/plugins/reject.py#L20

**Comment by jamtur01** [comment]
That's the behavior with current `master`.

```clojure
WARN [2016-12-27 07:22:03,842] defaultEventExecutorGroup-2-1 - riemann.config - empatico.etc.alerta$alerta@34fd6c91 threw
clojure.lang.ExceptionInfo: clj-http: status 403 {:status 403, :headers {"Content-Type" "application/json", "Access-Control-Allow-Origin" "http://explorer.alerta.io", "Vary" "Origin", "Content-Length" "107", "Server" "Werkzeug/0.11.13 Python/2.7.13", "Date" "Tue, 27 Dec 2016 12:22:03 GMT"}, :body "{\n  \"message\": \"[POLICY] Alert environment must be one of Production, Development\", \n  \"status\": \"error\"\n}\n", :request-time 393, :trace-redirects ["http://localhost:8080/webhooks/riemann"], :orig-content-encoding nil}
	at slingshot.support$stack_trace.invoke(support.clj:201)
	at clj_http.client$wrap_exceptions$fn__2442.invoke(client.clj:195)
	at clj_http.client$wrap_accept$fn__2602.invoke(client.clj:562)
	at clj_http.client$wrap_accept_encoding$fn__2608.invoke(client.clj:579)
	at clj_http.client$wrap_content_type$fn__2597.invoke(client.clj:554)
	at clj_http.client$wrap_form_params$fn__2679.invoke(client.clj:726)
	at clj_http.client$wrap_nested_params$fn__2693.invoke(client.clj:760)
	at clj_http.client$wrap_method$fn__2649.invoke(client.clj:670)
	at clj_http.cookies$wrap_cookies$fn__172.invoke(cookies.clj:124)
	at clj_http.links$wrap_links$fn__1073.invoke(links.clj:51)
	at clj_http.client$wrap_unknown_host$fn__2702.invoke(client.clj:776)
	at clj_http.client$post.invokeStatic(client.clj:891)
	at clj_http.client$post.doInvoke(client.clj:887)
	at clojure.lang.RestFn.invoke(RestFn.java:423)
	at empatico.etc.alerta$post_to_alerta.invokeStatic(alerta.clj:23)
	at empatico.etc.alerta$post_to_alerta.invoke(alerta.clj:18)
	at empatico.etc.alerta$alerta.invokeStatic(alerta.clj:57)
	at empatico.etc.alerta$alerta.invoke(alerta.clj:53)
	at riemann.config$eval5654$stream__5658$fn__5663.invoke(riemann.config:25)
	at riemann.config$eval5654$stream__5658.invoke(riemann.config:25)
	at riemann.streams$default$stream__2582$fn__2593.invoke(streams.clj:1354)
	at riemann.streams$default$stream__2582.invoke(streams.clj:1354)
	at riemann.core$stream_BANG_$fn__3279.invoke(core.clj:19)
	at riemann.core$stream_BANG_.invokeStatic(core.clj:18)
	at riemann.core$stream_BANG_.invoke(core.clj:14)
	at riemann.transport$handle.invokeStatic(transport.clj:167)
	at riemann.transport$handle.invoke(transport.clj:161)
	at riemann.transport.udp$udp_handler.invokeStatic(udp.clj:53)
	at riemann.transport.udp$udp_handler.invoke(udp.clj:50)
	at riemann.transport.udp$gen_udp_handler$fn__5162.invoke(udp.clj:43)
	at riemann.transport.udp.proxy$io.netty.channel.ChannelInboundHandlerAdapter$ff19274a.channelRead(Unknown Source)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:38)
	at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:363)
	at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:66)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:877)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)
INFO [2016-12-27 07:22:03,960] defaultEventExecutorGroup-2-1 - riemann.config - #riemann.codec.Event{:host web3, :service api latency, :state warning, :description 63.5 milliseconds per request, :metric 63.5, :tags [tag1 tag2], :time 1482841313, :ttl 60.0, :environment production, :group jane}
```

This is with the event:

```json
{
  host: 'web3',
  service: 'api latency',
  state: 'warning',
  metric: 63.5,
  description: "63.5 milliseconds per request",
  tags: [ 'tag1', 'tag2' ],
  time: Time.now.to_i - 10,
  ttl: 60,
  environment: 'production',
  group: 'jane'
}
```

If I change the event to:

```json
{
  host: 'web3',
  service: 'api latency',
  state: 'warning',
  metric: 63.5,
  description: "63.5 milliseconds per request",
  tags: [ 'tag1', 'tag2' ],
  time: Time.now.to_i - 10,
  ttl: 60,
  environment: 'Production',
  group: 'jane'
}
```

Then we're all good:

```clojure
INFO [2016-12-27 07:23:44,132] defaultEventExecutorGroup-2-1 - riemann.config - #riemann.codec.Event{:host web3, :service api latency, :state warning, :description 63.5 milliseconds per request, :metric 63.5, :tags [tag1 tag2], :time 1482841414, :ttl 60.0, :environment Production, :group jane}
```

**Comment by satterly** [comment]
I see. This is the correct behaviour. I had missed the fact that you had set the allowed environments to lowercase `production`, `development`, and `code`.

It doesn't matter to Alerta if you use upper or lowercase but you should be consistent otherwise it complicates the de-duplication and correlation logic. I'd have to lowercase everything first before doing an alert comparison and then do I do the same thing when generating aggregated API responses?

Much simpler and less surprising, in my opinion, to enforce strict case sensitivity when ingesting alerts however it is entirely optional. You are free to disable the "reject" plugin completely if you have a different use case.

**Comment by jamtur01** [comment]
No makes sense. I wasn't aware it was tied to the dedup logic.

**Comment by sosoriov** [comment]
@satterly I'm having similar issues in my configuration

i got this message:
``` bash
WARNING:alerta.plugins:[POLICY] Alert environment does not match one of prod, test, acpt, dvlp
```

and I'm passing this setting to my docker container

```
-e ALLOWED_ENVIRONMENTS="prod,test,acpt,dvlp"
```

Thanks for your help

**Comment by satterly** [comment]
I don't see how this is related to the original issue.
