### ISSUE TITLE
Issue deploying to apache with mod_wsgi

### ISSUE THREAD

**Issue by jaxxstorm** [guardian/alerta#333]
I feel like this is something really simple, but I'm struggling to get this deployed.

I have a virtualenv with alerta-server installed:

```
root@sensu:/var/log/httpd # /opt/alerta/bin/pip list
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
alerta-server (4.8.25)
bcrypt (3.1.2)
cffi (1.9.1)
click (6.7)
Flask (0.12)
Flask-Cors (3.0.2)
itsdangerous (0.24)
Jinja2 (2.9.4)
MarkupSafe (0.23)
pip (9.0.1)
pycparser (2.17)
PyJWT (1.4.2)
pymongo (3.4.0)
python-dateutil (2.6.0)
pytz (2016.10)
requests (2.12.4)
setuptools (32.3.1)
six (1.10.0)
Werkzeug (0.11.15)
wheel (0.29.0)
```

I have a `.wsgi` file

```
# cat /var/www/alerta.wsgi
#!/usr/bin/python
activate_this = '/opt/alerta/bin/activate_this.py'
execfile(activate_this, dict(__file__=activate_this))
from alerta.app import app as application
```

And then finally, an apache vhost:

```
root@sensu:/var/log/httpd # cat /etc/httpd/conf.d/alerta.conf
Listen 8080
<VirtualHost *:8080>
 ServerName <hostname>
  WSGIDaemonProcess alerta processes=5 threads=5
  WSGIProcessGroup alerta
  WSGIScriptAlias / /var/www/alerta.wsgi
  WSGIPassAuthorization On
  <Directory /opt/alerta>
    WSGIApplicationGroup %{GLOBAL}
    Require all granted
  </Directory>
</VirtualHost>
```

However, when I start `http` and browse to <hostname>:8080, I get an error:

```
[Tue Jan 10 21:04:35.282559 2017] [:error] [pid 24927] --------------------------------------------------------------------------------
[Tue Jan 10 21:04:35.282590 2017] [:error] [pid 24927] INFO in mongo [/opt/alerta/lib/python2.7/site-packages/alerta/app/database/mongo.py:57]:
[Tue Jan 10 21:04:35.282594 2017] [:error] [pid 24927] MongoDB Client: Connected to mongodb://localhost:27017/monitoring
[Tue Jan 10 21:04:35.282596 2017] [:error] [pid 24927] --------------------------------------------------------------------------------
[Tue Jan 10 21:04:37.283604 2017] [:error] [pid 24927] [remote 192.168.4.109:236] mod_wsgi (pid=24927): Target WSGI script '/var/www/alerta.wsgi' cannot be loaded as Python module.
[Tue Jan 10 21:04:37.283763 2017] [:error] [pid 24927] [remote 192.168.4.109:236] mod_wsgi (pid=24927): Exception occurred processing WSGI script '/var/www/alerta.wsgi'.
[Tue Jan 10 21:04:37.283794 2017] [:error] [pid 24927] [remote 192.168.4.109:236] Traceback (most recent call last):
[Tue Jan 10 21:04:37.283814 2017] [:error] [pid 24927] [remote 192.168.4.109:236]   File "/var/www/alerta.wsgi", line 4, in <module>
[Tue Jan 10 21:04:37.284129 2017] [:error] [pid 24927] [remote 192.168.4.109:236]     from alerta.app import app as application
[Tue Jan 10 21:04:37.284148 2017] [:error] [pid 24927] [remote 192.168.4.109:236]   File "/opt/alerta/lib/python2.7/site-packages/alerta/app/__init__.py", line 97, in <module>
[Tue Jan 10 21:04:37.284201 2017] [:error] [pid 24927] [remote 192.168.4.109:236]     db = conn.connect()
[Tue Jan 10 21:04:37.284211 2017] [:error] [pid 24927] [remote 192.168.4.109:236]   File "/opt/alerta/lib/python2.7/site-packages/alerta/app/database/utils.py", line 20, in connect
[Tue Jan 10 21:04:37.284238 2017] [:error] [pid 24927] [remote 192.168.4.109:236]     return backend.Database()
[Tue Jan 10 21:04:37.284247 2017] [:error] [pid 24927] [remote 192.168.4.109:236]   File "/opt/alerta/lib/python2.7/site-packages/alerta/app/database/mongo.py", line 32, in __init__
[Tue Jan 10 21:04:37.284475 2017] [:error] [pid 24927] [remote 192.168.4.109:236]     self.connect()
[Tue Jan 10 21:04:37.284487 2017] [:error] [pid 24927] [remote 192.168.4.109:236]   File "/opt/alerta/lib/python2.7/site-packages/alerta/app/database/mongo.py", line 63, in connect
[Tue Jan 10 21:04:37.284501 2017] [:error] [pid 24927] [remote 192.168.4.109:236]     LOG.info('MongoDB Client: MongoDB v%s, using database "%s"', self.get_version(), self.get_db_name())
[Tue Jan 10 21:04:37.284508 2017] [:error] [pid 24927] [remote 192.168.4.109:236]   File "/opt/alerta/lib/python2.7/site-packages/alerta/app/database/mongo.py", line 82, in get_version
[Tue Jan 10 21:04:37.284517 2017] [:error] [pid 24927] [remote 192.168.4.109:236]     return self.db.client.server_info()['version']
[Tue Jan 10 21:04:37.284523 2017] [:error] [pid 24927] [remote 192.168.4.109:236]   File "/opt/alerta/lib/python2.7/site-packages/pymongo/mongo_client.py", line 1143, in server_info
[Tue Jan 10 21:04:37.284737 2017] [:error] [pid 24927] [remote 192.168.4.109:236]     read_preference=ReadPreference.PRIMARY)
[Tue Jan 10 21:04:37.284750 2017] [:error] [pid 24927] [remote 192.168.4.109:236]   File "/opt/alerta/lib/python2.7/site-packages/pymongo/database.py", line 491, in command
[Tue Jan 10 21:04:37.284939 2017] [:error] [pid 24927] [remote 192.168.4.109:236]     with client._socket_for_reads(read_preference) as (sock_info, slave_ok):
[Tue Jan 10 21:04:37.284950 2017] [:error] [pid 24927] [remote 192.168.4.109:236]   File "/usr/lib64/python2.7/contextlib.py", line 17, in __enter__
[Tue Jan 10 21:04:37.285017 2017] [:error] [pid 24927] [remote 192.168.4.109:236]     return self.gen.next()
[Tue Jan 10 21:04:37.285028 2017] [:error] [pid 24927] [remote 192.168.4.109:236]   File "/opt/alerta/lib/python2.7/site-packages/pymongo/mongo_client.py", line 859, in _socket_for_reads
[Tue Jan 10 21:04:37.285038 2017] [:error] [pid 24927] [remote 192.168.4.109:236]     with self._get_socket(read_preference) as sock_info:
[Tue Jan 10 21:04:37.285044 2017] [:error] [pid 24927] [remote 192.168.4.109:236]   File "/usr/lib64/python2.7/contextlib.py", line 17, in __enter__
[Tue Jan 10 21:04:37.285051 2017] [:error] [pid 24927] [remote 192.168.4.109:236]     return self.gen.next()
[Tue Jan 10 21:04:37.285056 2017] [:error] [pid 24927] [remote 192.168.4.109:236]   File "/opt/alerta/lib/python2.7/site-packages/pymongo/mongo_client.py", line 823, in _get_socket
[Tue Jan 10 21:04:37.285063 2017] [:error] [pid 24927] [remote 192.168.4.109:236]     server = self._get_topology().select_server(selector)
[Tue Jan 10 21:04:37.285069 2017] [:error] [pid 24927] [remote 192.168.4.109:236]   File "/opt/alerta/lib/python2.7/site-packages/pymongo/topology.py", line 214, in select_server
[Tue Jan 10 21:04:37.285162 2017] [:error] [pid 24927] [remote 192.168.4.109:236]     address))
[Tue Jan 10 21:04:37.285172 2017] [:error] [pid 24927] [remote 192.168.4.109:236]   File "/opt/alerta/lib/python2.7/site-packages/pymongo/topology.py", line 189, in select_servers
[Tue Jan 10 21:04:37.285182 2017] [:error] [pid 24927] [remote 192.168.4.109:236]     self._error_message(selector))
[Tue Jan 10 21:04:37.285196 2017] [:error] [pid 24927] [remote 192.168.4.109:236] ServerSelectionTimeoutError: No servers found yet
```

I've checked mongo, that's fine
I've checked all the deps and perms, they also seem fine.

Is this something silly? What am I missing?

**Comment by satterly** [comment]
What happens if you move the `WSGIApplicationGroup %{GLOBAL} ` line to just below the `WSGIProcessGroup alerta` ? Like this https://github.com/alerta/alerta-cloudformation/blob/master/Alerta_Single_Instance.yaml#L141

**Comment by jaxxstorm** [comment]
Aha! That worked!
Is there a reason this is needed? Would like to understand what I just did :)

**Comment by satterly** [comment]
Pymongo 3.x changed so that it now requires each child process of forked applications (such as an apache wsgi app) to create their own instances of the mongo client. For more information see this [stackoverflow question](http://stackoverflow.com/questions/31030307/why-is-pymongo-3-giving-serverselectiontimeouterror), this pymongo [faq](https://api.mongodb.com/python/current/faq.html#is-pymongo-fork-safe) and this [mongo Jira ticket](https://jira.mongodb.org/browse/PYTHON-986?focusedCommentId=1019680&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1019680).

**Comment by satterly** [comment]
Where did you get that example apache vhost `alertad.conf` file? I should fix it at source and update the docs.

**Comment by satterly** [comment]
I've updated all references that I can find to `WSGIApplicationGroup %{GLOBAL}` and expanded on the example in the [FAQ section](http://docs.alerta.io/en/latest/faq.html#what-s-this-mongodb-serverselectiontimeouterror) of the docs website. I also found a new reference on the PyMongo site that explicitly addresses this issue. See http://api.mongodb.com/python/current/examples/mod_wsgi.html
