### ISSUE TITLE
Angular UI locks Alertad server

### ISSUE THREAD

**Issue by thomasfowler** [guardian/alerta#78]
If you leave an instance of the [Alerta Angular Frontend](https://github.com/alerta/angular-alerta-webui) running, it occasionally locks the alertad server. Any further incoming alerts are not processed by the server, output on stdout or available through the API.

The following is the stack trace output when you keyboard interrupt the running process:
```bsh
197.228.171.62 - - [18/Feb/2015 05:50:20] "GET /alerts/count HTTP/1.1" 200 -
^C----------------------------------------
Exception happened during processing of request from ('197.228.171.62', 52068)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 568, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 203, in handle
----------------------------------------
Exception happened during processing of request from ('197.228.171.62', 51739)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 568, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 203, in handle
----------------------------------------
    rv = BaseHTTPRequestHandler.handle(self)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 234, in handle_one_request
    self.raw_requestline = self.rfile.readline()
  File "/usr/lib/python2.7/socket.py", line 447, in readline
    data = self._sock.recv(self._rbufsize)
Exception happened during processing of request from ('146.148.121.4', 41429)
Traceback (most recent call last):
    rv = BaseHTTPRequestHandler.handle(self)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
KeyboardInterrupt
----------------------------------------
  File "/usr/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 234, in handle_one_request
    self.raw_requestline = self.rfile.readline()
  File "/usr/lib/python2.7/SocketServer.py", line 555, in process_request
    self.collect_children()
  File "/usr/lib/python2.7/socket.py", line 447, in readline
    data = self._sock.recv(self._rbufsize)
  File "/usr/lib/python2.7/SocketServer.py", line 523, in collect_children
    pid, status = os.waitpid(0, 0)
KeyboardInterrupt
----------------------------------------
KeyboardInterrupt
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('197.228.171.62', 55571)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 568, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 203, in handle
    rv = BaseHTTPRequestHandler.handle(self)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 234, in handle_one_request
    self.raw_requestline = self.rfile.readline()
  File "/usr/lib/python2.7/socket.py", line 447, in readline
    data = self._sock.recv(self._rbufsize)
KeyboardInterrupt
```
The IP address in the stack trace above is the public IP of the client accessing the angular UI at the time. So, this is not an issue with posting alerts to the alerta server but rather with getting alerts from the API.

However, hitting ctrl-c doesn't kill the process, but rather seems to kill the lock and any other alerts that have been sent in the interim, now flush through and the process continues.

I'm not sure if this should be raised here or on the Alerta angular UI project.

**Comment by satterly** [comment]
Thanks for reporting this but I'll need a bit more information...

  * What version of alertad are you running?
  * Are you running alertad as a single-threaded process or as a WSGI app using apache or nginx?
  * Are you running an up-to-date version of the alerta web UI?
  * Are you running any `plugins`?
  * How many alerts do you have in the mongo database?
  * How long does it take before you notice this behaviour?
  * Can you think of anything else I might need to know to reproduce the problem?

**Comment by thomasfowler** [comment]
- Latest version: 4.0.10
- Single threaded using the alertad daemon
- Using the latest version of Web UI from the Github repo (so whatever is in the master branch right now)
- Only what was in the default config. Reject and AMQP
- 56 Alerts in the DB
- Usually a long time - like leaving the UI open for 10 hours or so

In all honesty, we're battling to reproduce the problem ourselves. We've experienced it a few times now, but when it occurs, it's quite random.

At your suggestion, happy to reproduce any other logs that may help.

**Comment by satterly** [comment]
I can't be 100% sure but I'd guess it has something to do with the number of processes being set to `3` here ... https://github.com/guardian/alerta/blob/master/alerta/app/__init__.py#L44

> Would you recommend, in a production environment, to run Alerta on something like Apache or nginx?

Yes, I only ever run `alertad` like you are now during development. Alerta is designed to run as a WSGI application behind Apache or nginx and that's the only way I've ever run it in production environments.

There are quite a few examples of how to run it as a WSGI app behind a web server (or using gunicorn) [here](https://github.com/alerta/vagrant-try-alerta/blob/master/scripts/alerta.sh), [here](https://github.com/alerta/alerta-cfn/blob/master/Alerta_Single_Instance.template), [here](https://github.com/alerta/openshift-api-alerta/blob/master/wsgi.py), and [here](https://github.com/alerta/docker-alerta/blob/master/supervisord.conf).

It's pretty straight-forward but let me know if you have any trouble getting `alerta` running that way.

**Comment by thomasfowler** [comment]
Awesome! Thanks for the heads up on this. I've configured it to run on our Apache instance. I'll let you know how it goes and if we run into the same issue with this config.
