### ISSUE TITLE
API key fail to generate

### ISSUE THREAD

**Issue by menardorama** [guardian/alerta#86]
When trying to generate a new api key, I get the following error in alertad : 
```
[Tue Apr 21 19:02:19 2015] [error] 2015-04-21 19:02:19,883 - alerta.app.cors[24193]: INFO - Request from Origin:http://alerta.emv2.com, setting Access-Control-Allow-Origin:http://alerta.emv2.com
[Tue Apr 21 19:02:19 2015] [error] 2015-04-21 19:02:19,890 - alerta.app[24193]: ERROR - Exception on /key [POST]
[Tue Apr 21 19:02:19 2015] [error] Traceback (most recent call last):
[Tue Apr 21 19:02:19 2015] [error]   File "/opt/alerta/lib/python2.6/site-packages/flask/app.py", line 1817, in wsgi_app
[Tue Apr 21 19:02:19 2015] [error]     response = self.full_dispatch_request()
[Tue Apr 21 19:02:19 2015] [error]   File "/opt/alerta/lib/python2.6/site-packages/flask/app.py", line 1477, in full_dispatch_request
[Tue Apr 21 19:02:19 2015] [error]     rv = self.handle_user_exception(e)
[Tue Apr 21 19:02:19 2015] [error]   File "/opt/alerta/lib/python2.6/site-packages/flask_cors/extension.py", line 110, in wrapped_function
[Tue Apr 21 19:02:19 2015] [error]     return cors_after_request(app.make_response(f(*args, **kwargs)))
[Tue Apr 21 19:02:19 2015] [error]   File "/opt/alerta/lib/python2.6/site-packages/flask/app.py", line 1381, in handle_user_exception
[Tue Apr 21 19:02:19 2015] [error]     reraise(exc_type, exc_value, tb)
[Tue Apr 21 19:02:19 2015] [error]   File "/opt/alerta/lib/python2.6/site-packages/flask/app.py", line 1475, in full_dispatch_request
[Tue Apr 21 19:02:19 2015] [error]     rv = self.dispatch_request()
[Tue Apr 21 19:02:19 2015] [error]   File "/opt/alerta/lib/python2.6/site-packages/flask/app.py", line 1461, in dispatch_request
[Tue Apr 21 19:02:19 2015] [error]     return self.view_functions[rule.endpoint](**req.view_args)
[Tue Apr 21 19:02:19 2015] [error]   File "/opt/alerta/lib/python2.6/site-packages/flask_cors/decorator.py", line 120, in wrapped_function
[Tue Apr 21 19:02:19 2015] [error]     resp = make_response(f(*args, **kwargs))
[Tue Apr 21 19:02:19 2015] [error]   File "/opt/alerta/lib/python2.6/site-packages/alerta/app/auth.py", line 94, in decorated
[Tue Apr 21 19:02:19 2015] [error]     payload = parse_token(token)
[Tue Apr 21 19:02:19 2015] [error]   File "/opt/alerta/lib/python2.6/site-packages/alerta/app/auth.py", line 53, in parse_token
[Tue Apr 21 19:02:19 2015] [error]     return jwt.decode(token, key=app.config['SECRET_KEY'], audience=app.config['OAUTH2_CLIENT_ID'])
[Tue Apr 21 19:02:19 2015] [error]   File "/opt/alerta/lib/python2.6/site-packages/jwt/api.py", line 137, in decode
[Tue Apr 21 19:02:19 2015] [error]     self._validate_claims(payload, options=merged_options, **kwargs)
[Tue Apr 21 19:02:19 2015] [error]   File "/opt/alerta/lib/python2.6/site-packages/jwt/api.py", line 216, in _validate_claims
[Tue Apr 21 19:02:19 2015] [error]     raise InvalidIssuedAtError('Issued At claim (iat) cannot be in the future.')
[Tue Apr 21 19:02:19 2015] [error] InvalidIssuedAtError: Issued At claim (iat) cannot be in the future.
[Tue Apr 21 19:02:19 2015] [error] 2015-04-21 19:02:19,891 - alerta.app.cors[24193]: INFO - Request from Origin:http://alerta.emv2.com, setting Access-Control-Allow-Origin:http://alerta.emv2.com
```

**Comment by menardorama** [comment]
I had to remove the 2 following lines to get it work in /opt/alerta/lib/python2.6/site-packages/jwt/api.py
           if iat > (now + leeway):
               raise InvalidIssuedAtError('Issued At claim (iat) cannot be in the future.')


But that's just a trick

**Comment by satterly** [comment]
Is the server you are running alerta on time synced? Definitely check that `ntpd` is running and that `date` doesn't return an time in the future.

**Comment by menardorama** [comment]
Both were running on the same server....

can it be an issue if my server time is not as my client computer time ?

**Comment by satterly** [comment]
The server where `alertad` is running and the client where you have your web browser need to be time synced. They don't need to be the same time zone, though. We have our Alerta servers configured to use UTC time and people log in from their laptops set to local time (in the UK and Australia) and it all works fine.
