### ISSUE TITLE
Basic Auth broken

### ISSUE THREAD

**Issue by satterly** [guardian/alerta#91]
```
2015-06-11T00:31:19.977896+00:00 heroku[router]: at=info method=OPTIONS path="/auth/signup" host=alerta-api.herokuapp.com request_id=0783a919-0c66-4231-8d9f-3130e305a890 fwd="109.157.221.123" dyno=web.1 connect=1ms service=4ms status=200 bytes=468
2015-06-11T00:31:20.626010+00:00 heroku[router]: at=info method=POST path="/auth/signup" host=alerta-api.herokuapp.com request_id=9e09b7f9-3a93-4a54-a312-91b3306cc79f fwd="109.157.221.123" dyno=web.1 connect=14ms service=403ms status=500 bytes=568
2015-06-11T00:31:20.625983+00:00 app[web.1]: Traceback (most recent call last):
2015-06-11T00:31:20.625976+00:00 app[web.1]: 2015-06-11 00:31:20,625 - alerta.app[9]: ERROR - Exception on /auth/signup [POST]
2015-06-11T00:31:20.625985+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
2015-06-11T00:31:20.625992+00:00 app[web.1]:     rv = self.handle_user_exception(e)
2015-06-11T00:31:20.625989+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
2015-06-11T00:31:20.625987+00:00 app[web.1]:     response = self.full_dispatch_request()
2015-06-11T00:31:20.625993+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask_cors.py", line 272, in wrapped_function
2015-06-11T00:31:20.625996+00:00 app[web.1]:     return cors_after_request(app.make_response(f(*args, **kwargs)))
2015-06-11T00:31:20.626000+00:00 app[web.1]:     reraise(exc_type, exc_value, tb)
2015-06-11T00:31:20.625998+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
2015-06-11T00:31:20.626001+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
2015-06-11T00:31:20.626003+00:00 app[web.1]:     rv = self.dispatch_request()
2015-06-11T00:31:20.626011+00:00 app[web.1]:   File "/app/alerta/app/auth.py", line 158, in signup
2015-06-11T00:31:20.626014+00:00 app[web.1]:   File "/app/alerta/app/database.py", line 918, in get_user
2015-06-11T00:31:20.626005+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
2015-06-11T00:31:20.626009+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask_cors.py", line 152, in wrapped_function
2015-06-11T00:31:20.626010+00:00 app[web.1]:     resp = make_response(f(*args, **kwargs))
2015-06-11T00:31:20.626017+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/pymongo/collection.py", line 798, in find_one
2015-06-11T00:31:20.626019+00:00 app[web.1]:     for result in cursor.limit(-1):
2015-06-11T00:31:20.626007+00:00 app[web.1]:     return self.view_functions[rule.endpoint](**req.view_args)
2015-06-11T00:31:20.626013+00:00 app[web.1]:     user = db.get_user(user_id)
2015-06-11T00:31:20.626016+00:00 app[web.1]:     user = self.db.users.find_one({"_id": id})
2015-06-11T00:31:20.626026+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/pymongo/cursor.py", line 813, in __send_message
2015-06-11T00:31:20.626020+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/pymongo/cursor.py", line 983, in next
2015-06-11T00:31:20.626027+00:00 app[web.1]:     **kwargs)
2015-06-11T00:31:20.626023+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/pymongo/cursor.py", line 908, in _refresh
2015-06-11T00:31:20.626024+00:00 app[web.1]:     self.__read_preference))
2015-06-11T00:31:20.626029+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/pymongo/mongo_client.py", line 744, in _send_message_with_response
2015-06-11T00:31:20.626021+00:00 app[web.1]:     if len(self.__data) or self._refresh():
2015-06-11T00:31:20.626040+00:00 app[web.1]: InvalidDocument: Cannot encode object: <pymongo.results.InsertOneResult object at 0x7f3b7ce78140>
2015-06-11T00:31:20.626030+00:00 app[web.1]:     exhaust)
2015-06-11T00:31:20.626032+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/pymongo/mongo_client.py", line 755, in _reset_on_error
2015-06-11T00:31:20.626035+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/pymongo/server.py", line 85, in send_message_with_response
2015-06-11T00:31:20.626036+00:00 app[web.1]:     set_slave_okay, sock_info.is_mongos)
2015-06-11T00:31:20.626038+00:00 app[web.1]:     self.ntoreturn, spec, self.fields, self.codec_options)
2015-06-11T00:31:20.626033+00:00 app[web.1]:     return func(*args, **kwargs)
2015-06-11T00:31:20.626037+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/pymongo/message.py", line 107, in get_message
```

**Comment by satterly** [comment]
Fixed by #93 -- missed a PyMongo 3.0 change.
